version: '3.9'

services:
  your_ckp_name:
    image: ghcr.io/huggingface/text-generation-inference:sha-4cce843
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=16384
      - DTYPE=bfloat16
      - NUM_SHARD=1
    volumes:
      - ./query_attack_cpk:/query_attack
    ports:
      - "30009:80"
      - "30010:80"
    command:
      - "--model-id"
      - "/query_attack/your_ckp_name"
    deploy:
      resources:
        reservations:
          memory: 8g
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
